config/routes.rb
ColtonSite::Application.routes.draw do
  root 'static_pages#home'
  match '/about',       to: 'static_pages#about', via: 'get'
  match '/blog',        to: 'static_pages#blog', via: 'get'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def blog
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-47886901-1', 'coltonseal.com');
  ga('send', 'pageview');

</script>
  <title>Colton Seal</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<h1><%= link_to "COLTON SEAL", root_path %></h1>
	<div class = "underline"></div>
	<!--[if !(lte IE 8)]><!-->
<script type="text/javascript">
  (function(){
    var e = document.createElement('script'); e.type='text/javascript'; e.async = true;
    e.src = document.location.protocol + '//d1agz031tafz8n.cloudfront.net/thedaywefightback.js/widget.min.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(e, s);
  })();
</script>
<!--<![endif]-->


<div class = "container">
<%= yield %>
</div>

</body>
</html>

app/views/static_pages/about.html.erb
<div id = "main">
	<div id = "posts">
		<h1>About Me</h1>
		<article>Hi im Colton.  Im interested in start-ups, programming, databases, and design.  I have a rottweiler named Lucy, a bulldog stepchild named Capone, and a beautiful girlfriend, Nikki.  If you want to get in contact, give me shout, my contact info is below.</article>
		<p>colton <small>(at)</small> coltonseal <small>(dot)</small> com</p>
		<p>(two one four) 205 - eight two two three</p>
		<p></p>
		<p></p>
		<p></p>
		<p></p>
		<h1>SiteS</h1>
		<p>faketweet.herokuapp.com</p>
		<p>www.rangairemfg.com</p>
		<p>www.abelidea.com</p>
	</div>
</div>

app/views/static_pages/blog.html.erb
<div id = "main">
	<div id = "posts">
		<h1>This is my first post.</h1>
		<article>This is my first blog post.  Right now I have nothing to do other than gain
		valuable knowledge building my own blogging management system.</article>
		<h3>Steps:</h3>
		<ul>
			<li>Create a css framework</li>
			<li>Generate a view or a template, make it accesible on call from terminal</li>
			<li>Create an admin front end that allows me to manage posts</li>
		</ul>
		<article>This should be an interesting project.  I know that rails makes it very easy to create a little blogging platform, but I will be doing this as much as I can from scratch, so that I can learn as much as possible.  If all else fails I can always use <%= link_to 'Ghost', "https://ghost.org/" %>.</article>
	</div>
</div>

app/views/static_pages/home.html.erb
<!-- This is was for the daywefight back.
<div class = "space"></div>
<p class = "text">CHECK OUT THE FORM BELOW, PLEASE FILL IT OUT</p>
<p class = "textsmall">(email is the easiest)

<p>|</p>
<p>|</p>

<p class = "arrow-left">\</p>
<p class = "arrow-right">/</p>
-->
<div class = "space"></div>
<!--<p class = "text"><%#=link_to "BLOG", blog_path %></p>-->
<p class = "text"><%=link_to "ABOUT", about_path %></p>